"""Generate the shared common-function library under falcom/ed9/writer/metadata/common/ from a
corpus of decompiled .dat scripts.

Usage:
    python falcom/ed9/writer/scp_writer_gen_common_funcs.py <corpus_root>

Every run is a full rewrite: the whole output directory is cleared and regenerated from scratch, so
hand edits to generated files don't survive - change this script instead.

Algorithm:
    1. Walk the corpus in sorted order, disassembling every is_common_func function
       (round_trip=False, keep_unreachable_code=False) and fingerprinting it (metadata/signature.py).
    2. Per name, the majority fingerprint is canonical; ties go to the first occurrence in sorted
       order. This is a two-pass design: pass 1 only fingerprints (cheap, keeps every occurrence's
       digest), pass 2 re-parses just the winning files to extract full render data.
    3. Any canonical function touching LOAD_GLOBAL/SET_GLOBAL is excluded, then the exclusion is
       closed over CALL targets to a fixed point. Every included function's CALL targets must
       themselves be included, or generation fails loudly.
    4. Included functions are grouped by first-syscall subsystem into one module per subsystem
       (no-syscall functions share one module), then rendered from the instruction stream -
       operand-level substitution, never text rewriting - and written out. A common_all.py module
       re-exporting every generated module is also written, so a script can bring the whole
       library into scope with one import regardless of which functions its own source used.
"""

import argparse
import keyword
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from common.config import default_indent
from falcom.ed9.disasm.ed9_optable import ED9Opcode, ED9OperandType
from falcom.ed9.disasm.formatter import Formatter, FormatterContext
from falcom.ed9.disasm.instruction import Instruction
from falcom.ed9.disasm.instruction_table import OperandType
from falcom.ed9.parser.scp import ScpParser
from falcom.ed9.parser.types_parser import Function, FunctionParam
from falcom.ed9.writer import scp_writer_helper
from falcom.ed9.writer.metadata import COMMON_LIBRARY_PACKAGE, SCP_WRITER_HELPER_IMPORT
from falcom.ed9.writer.metadata.signature import function_fingerprint, fingerprint_digest

DAT_PATTERN = '*.dat'
OUTPUT_DIR = Path(__file__).resolve().parent / 'metadata' / 'common'
INDEX_PATH = Path(__file__).resolve().parent / 'metadata' / 'common_index.py'
ALL_PATH = Path(__file__).resolve().parent / 'metadata' / 'common_all.py'
MODULE_PREFIX = 'scp_writer_common_'
NO_SYSCALL_MODULE = f'{MODULE_PREFIX}no_syscall'
GENERATED_HEADER_COMMENT = '# Auto-generated by scp_writer_gen_common_funcs.py - do not edit by hand'

# Every name a generated module's own "from ...scp_writer_helper import *" line brings into scope -
# a canonical function reusing one would silently shadow it for the rest of that module's file.
RESERVED_HELPER_NAMES = {name for name in vars(scp_writer_helper) if not name.startswith('_')}

# RenderedOp.kind tags - named rather than raw string literals, matching metadata/signature.py's tags
OFFSET_OPERAND  = 'offset'   # deferred: resolved to a genLabel() local once the function is rendered
FUNC_OPERAND    = 'func'     # deferred: resolved to a bare name or common_N.name once modules are assigned
LITERAL_OPERAND = 'literal'  # already-formatted Python source, independent of module assignment

# Names every generated .py script's own header/footer bind at module scope (scp.py's
# gen_python_header/gen_python_footer) - an imported common function reusing one of these would
# silently rebind it (e.g. a function named 'scena' would replace the writer, breaking the very next
# '@scena.CommonImports()' line the header emits). Unlike RESERVED_HELPER_NAMES this isn't a name
# used inside the library itself, so it can't be discovered by introspecting a library module.
EMITTED_SCRIPT_RESERVED_NAMES = {'scena', 'globalvars', 'commonImports', 'main'}


@dataclass
class RenderedOp:
    """One already-formatted operand, deferred only where module assignment or a label name is needed"""
    kind: str              # OFFSET_OPERAND | FUNC_OPERAND | LITERAL_OPERAND
    text: str | None = None      # LITERAL_OPERAND: ready-to-emit Python source
    callee: str | None = None    # FUNC_OPERAND: resolved callee name
    offset: int | None = None    # OFFSET_OPERAND: raw destination offset, function-local


@dataclass
class RenderedInst:
    offset: int
    mnemonic: str
    operands: list[RenderedOp]


@dataclass
class CanonicalFunction:
    name: str
    params: list[FunctionParam]
    instructions: list[RenderedInst]
    referenced_offsets: set[int]
    touches_global: bool
    call_targets: set[str]
    subsystem: int | None
    digest: str


def collect_paths(corpus_root: Path) -> list[Path]:
    return sorted(corpus_root.rglob(DAT_PATTERN))


def collect_occurrences(paths: list[Path]) -> dict[str, list[tuple[str, int]]]:
    """Pass 1: fingerprint every is_common_func occurrence. name -> [(digest, file_idx), ...]"""
    occurrences: dict[str, list[tuple[str, int]]] = {}

    for file_idx, path in enumerate(paths):
        parser, functions = ScpParser.load(path, round_trip = False, keep_unreachable_code = False)

        for func in functions:
            if not func.is_common_func:
                continue

            digest = fingerprint_digest(function_fingerprint(parser, func))
            occurrences.setdefault(func.name, []).append((digest, file_idx))

    return occurrences


def select_canonical(occurrences: dict[str, list[tuple[str, int]]]) -> dict[str, tuple[str, int]]:
    """Per name: the majority digest, ties broken by earliest first occurrence. name -> (digest, file_idx)"""
    canonical = {}

    for name, entries in occurrences.items():
        counts = Counter(digest for digest, _file_idx in entries)

        first_seen: dict[str, int] = {}
        for digest, file_idx in entries:  # entries are already in ascending file_idx order
            first_seen.setdefault(digest, file_idx)

        best_digest = max(counts, key = lambda d: (counts[d], -first_seen[d]))
        canonical[name] = (best_digest, first_seen[best_digest])

    return canonical


def extract_canonical_functions(canonical: dict[str, tuple[str, int]], paths: list[Path]) -> dict[str, CanonicalFunction]:
    """Pass 2: re-parse only the winning files (grouped, so a file shared by many names is parsed once)"""
    names_by_file_idx: dict[int, list[str]] = {}
    for name, (_digest, file_idx) in canonical.items():
        names_by_file_idx.setdefault(file_idx, []).append(name)

    result: dict[str, CanonicalFunction] = {}

    for file_idx, names in names_by_file_idx.items():
        path = paths[file_idx]
        parser, functions = ScpParser.load(path, round_trip = False, keep_unreachable_code = False)
        functions_by_name = {func.name: func for func in functions}

        for name in names:
            func = functions_by_name[name]
            expected_digest, _ = canonical[name]
            result[name] = render_canonical_function(parser, func, path, expected_digest)

    return result


def verify_canonical_function(parser: ScpParser, func: Function, path: Path, expected_digest: str) -> tuple[list[Instruction], set[int]]:
    """Verify func's fingerprint still matches pass 1's selection, and that every branch target it
    contains lands on a retained instruction - both fail loudly instead of letting a later stage (a
    corrupted digest, or the writer's own label xref patching) produce a confusing error. Returns
    the function's reachable instructions and referenced offsets for render_instructions to use."""
    digest = fingerprint_digest(function_fingerprint(parser, func))
    if digest != expected_digest:
        raise RuntimeError(f'{func.name}: fingerprint changed between pass 1 and pass 2 ({path})')

    instructions = parser.get_instructions(func)
    referenced_offsets = Formatter.find_referenced_offsets(func.entry_block)

    # Every branch target must land on a real instruction, or render_function would emit a jump to
    # a label that's never placed - the writer would only catch that later, as an opaque KeyError
    # on a UUID label name while patching xrefs. Mirrors formatter.py's own invariant
    # (referenced_offsets <= block_start_offsets) instead of relying on that check running elsewhere.
    unresolved = referenced_offsets - {inst.offset for inst in instructions}
    if unresolved:
        targets = ', '.join(f'0x{offset:X}' for offset in sorted(unresolved))
        raise RuntimeError(f'{func.name} ({path}): branch target(s) {targets} do not land on a retained instruction')

    return instructions, referenced_offsets


def render_instructions(parser: ScpParser, instructions: list[Instruction]) -> tuple[list[RenderedInst], bool, set[str], int | None]:
    """Render every instruction's operands, deferring Offset/Func operands for render_function's
    later label/module-qualification pass - everything else is formatted immediately since it never
    depends on where the function ends up living. Also collects, as a side effect of the same single
    pass: whether the body touches a global (the exclusion trigger), its CALL targets (the closure
    input), and its first-syscall subsystem (the module-grouping key)."""
    formatter_context = FormatterContext(
        get_func_name_from_func_id = parser.get_func_name_from_func_id,
        get_global_name_from_index = parser.get_global_name_from_index,
    )

    rendered_instructions = []
    touches_global = False
    call_targets: set[str] = set()
    subsystem = None

    for inst in instructions:
        if inst.opcode in (ED9Opcode.LOAD_GLOBAL, ED9Opcode.SET_GLOBAL):
            touches_global = True

        if subsystem is None and inst.opcode == ED9Opcode.SYSCALL:
            subsystem = inst.operands[0].value

        ops = []
        for op in inst.operands:
            if op.descriptor.type == OperandType.Offset:
                ops.append(RenderedOp(kind = OFFSET_OPERAND, offset = op.value))

            elif op.descriptor.type == ED9OperandType.Func:
                callee = parser.get_func_name_from_func_id(op.value)
                call_targets.add(callee)
                ops.append(RenderedOp(kind = FUNC_OPERAND, callee = callee))

            else:
                ops.append(RenderedOp(kind = LITERAL_OPERAND, text = op.descriptor.format_operand(op, formatter_context)))

        rendered_instructions.append(RenderedInst(offset = inst.offset, mnemonic = inst.descriptor.mnemonic, operands = ops))

    return rendered_instructions, touches_global, call_targets, subsystem


def render_canonical_function(parser: ScpParser, func: Function, path: Path, expected_digest: str) -> CanonicalFunction:
    instructions, referenced_offsets = verify_canonical_function(parser, func, path, expected_digest)
    rendered_instructions, touches_global, call_targets, subsystem = render_instructions(parser, instructions)

    return CanonicalFunction(
        name                = func.name,
        params              = func.params,
        instructions        = rendered_instructions,
        referenced_offsets  = referenced_offsets,
        touches_global      = touches_global,
        call_targets        = call_targets,
        subsystem           = subsystem,
        digest              = expected_digest,
    )


def compute_excluded(canon: dict[str, CanonicalFunction]) -> set[str]:
    """Direct global-var users, then closed over CALL targets to a fixed point"""
    excluded = {name for name, cf in canon.items() if cf.touches_global}

    changed = True
    while changed:
        changed = False
        for name, cf in canon.items():
            if name in excluded:
                continue

            if any(target in excluded for target in cf.call_targets):
                excluded.add(name)
                changed = True

    return excluded


def assign_modules(included: set[str], canon: dict[str, CanonicalFunction]) -> dict[str, str]:
    name_to_module = {}
    for name in included:
        subsystem = canon[name].subsystem
        name_to_module[name] = f'{MODULE_PREFIX}{subsystem}' if subsystem is not None else NO_SYSCALL_MODULE

    return name_to_module


def module_suffix(module_key: str) -> str:
    """The subsystem number, or 'no_syscall' - module_key with the common prefix stripped"""
    return module_key[len(MODULE_PREFIX):]


def module_alias(module_key: str) -> str:
    return 'common_' + module_suffix(module_key)


def validate_names(included: set[str], name_to_module: dict[str, str]):
    """Every generated name must be a usable, non-keyword Python identifier, and can't collide with
    a star-imported helper name, any module's cross-module alias, or a name every emitted script's
    own header/footer binds (scena, commonImports, ...) - any of those would silently shadow the
    real one, either inside the library module that defines it or inside the first script that
    imports it. Reserves every module's alias, not just the ones the function's own module currently
    needs, so a name that's safe today can't start colliding after a later regen adds a new
    cross-module call."""
    all_aliases = {module_alias(module_key) for module_key in set(name_to_module.values())}
    reserved = RESERVED_HELPER_NAMES | all_aliases | EMITTED_SCRIPT_RESERVED_NAMES

    for name in included:
        if not name.isidentifier() or keyword.iskeyword(name):
            raise RuntimeError(f'{name!r} is not a usable Python function name')

        if name in reserved:
            raise RuntimeError(f'{name!r} ({name_to_module[name]}) collides with a reserved name (opcode helper, cross-module alias, or emitted-script binding)')


def render_function(cf: CanonicalFunction, name_to_module: dict[str, str], own_module: str) -> list[str]:
    indent = default_indent()
    param_str = ', '.join(Formatter.format_param(i, param) for i, param in enumerate(cf.params))

    offset_to_local = {offset: f'L{i}' for i, offset in enumerate(sorted(cf.referenced_offsets))}

    lines = [f'def {cf.name}({param_str}):']

    for local in offset_to_local.values():
        lines.append(f'{indent}{local} = genLabel()')

    for inst in cf.instructions:
        if inst.offset in offset_to_local:
            lines.append(f"{indent}label({offset_to_local[inst.offset]})")

        args = []
        for op in inst.operands:
            if op.kind == OFFSET_OPERAND:
                if op.offset not in offset_to_local:
                    raise RuntimeError(f'{cf.name}: branch target 0x{op.offset:X} has no label')

                args.append(offset_to_local[op.offset])

            elif op.kind == FUNC_OPERAND:
                callee_module = name_to_module[op.callee]
                args.append(op.callee if callee_module == own_module else f'{module_alias(callee_module)}.{op.callee}')

            else:
                args.append(op.text)

        lines.append(f'{indent}{inst.mnemonic}({", ".join(args)})')

    if not cf.instructions:
        lines.append(f'{indent}pass')

    return lines


def render_module(module_key: str, names: list[str], canon: dict[str, CanonicalFunction], name_to_module: dict[str, str]) -> str:
    imported_modules = sorted({
        name_to_module[op.callee]
        for name in names
        for inst in canon[name].instructions
        for op in inst.operands
        if op.kind == FUNC_OPERAND and name_to_module[op.callee] != module_key
    })

    lines = [
        f'"""Common-function library, subsystem {module_suffix(module_key)}"""',
        '',
        GENERATED_HEADER_COMMENT,
        '',
        SCP_WRITER_HELPER_IMPORT,
    ]
    # Two generated modules can import each other (a function in A calls one in B and vice versa).
    # Safe: "import x.y as z" only binds the module object here, at import time; every reference to
    # z.callee happens inside a function body, executed later, by which point both modules have
    # finished importing - the same reason a script's own manifest can import from either freely.
    lines.extend(f'import {COMMON_LIBRARY_PACKAGE}.{other} as {module_alias(other)}' for other in imported_modules)
    lines.append('')

    # Only this module's own functions are re-exported, not the helper's star-imported names - a second
    # star import of those (common_all) turns aliases like Value32 into variables for type checkers
    lines.append('__all__ = (')
    lines.extend(f'    {name!r},' for name in sorted(names))
    lines.append(')')
    lines.append('')

    for name in sorted(names):
        lines.extend(render_function(canon[name], name_to_module, module_key))
        lines.append('')
        lines.append('')

    return '\n'.join(lines).rstrip() + '\n'


def render_index(canon: dict[str, CanonicalFunction], included: set[str], name_to_module: dict[str, str]) -> str:
    lines = [
        '"""Index of the common-function library: name -> (module, fingerprint digest)"""',
        '',
        GENERATED_HEADER_COMMENT,
        '',
        'COMMON_FUNCTIONS = {',
    ]
    for name in sorted(included):
        lines.append(f"    {name!r}: ({name_to_module[name]!r}, {canon[name].digest!r}),")

    lines.append('}')
    return '\n'.join(lines) + '\n'


def render_all(module_keys: list[str]) -> str:
    lines = [
        '"""Every common-function library module, re-exported in one place.',
        '',
        'Every generated script imports this unconditionally (falcom/ed9/parser/scp.py\'s',
        'gen_python_header), so the whole library is always in scope - not just the functions a',
        'script\'s own source happened to use - for adding a common function call by hand.',
        '',
        'COMMON_LIBRARY_GENERATED is False when this package hasn\'t been generated yet (a fresh',
        'checkout before scp_writer_gen_common_funcs.py has been run) - match_library_functions',
        'checks it before matching anything, so an ungenerated library safely falls back to fully',
        'inline output instead of a manifest that would reference an undefined name."""',
        '',
        GENERATED_HEADER_COMMENT,
        '',
        'from common.logging import log as _log',
        '',
        'try:',
    ]
    lines.extend(f'    from {COMMON_LIBRARY_PACKAGE}.{module_key} import *' for module_key in module_keys)
    lines.append('    COMMON_LIBRARY_GENERATED = True')
    lines.append('except ModuleNotFoundError:')
    lines.append("    _log.info('Shared common-function library not generated - run falcom/ed9/writer/scp_writer_gen_common_funcs.py <corpus_root> to build it')")
    lines.append('    COMMON_LIBRARY_GENERATED = False')
    return '\n'.join(lines) + '\n'


def write_output(canon: dict[str, CanonicalFunction], included: set[str], name_to_module: dict[str, str]):
    for stale in OUTPUT_DIR.glob('*.py'):
        stale.unlink()

    OUTPUT_DIR.mkdir(parents = True, exist_ok = True)
    (OUTPUT_DIR / '__init__.py').write_text('"""Generated common-function library modules, one per syscall subsystem"""\n', encoding = 'utf-8', newline = '\n')

    names_by_module: dict[str, list[str]] = {}
    for name in included:
        names_by_module.setdefault(name_to_module[name], []).append(name)

    for module_key, names in names_by_module.items():
        text = render_module(module_key, names, canon, name_to_module)
        (OUTPUT_DIR / f'{module_key}.py').write_text(text, encoding = 'utf-8', newline = '\n')

    INDEX_PATH.write_text(render_index(canon, included, name_to_module), encoding = 'utf-8', newline = '\n')
    ALL_PATH.write_text(render_all(sorted(names_by_module)), encoding = 'utf-8', newline = '\n')


def generate(corpus_root: Path) -> dict[str, CanonicalFunction]:
    paths = collect_paths(corpus_root)
    occurrences = collect_occurrences(paths)
    canonical = select_canonical(occurrences)
    canon = extract_canonical_functions(canonical, paths)

    excluded = compute_excluded(canon)
    included = set(canon) - excluded

    for name in included:
        for target in canon[name].call_targets:
            if target not in included:
                raise RuntimeError(f'{name}: CALL target {target!r} is excluded or not a common function')

    name_to_module = assign_modules(included, canon)
    validate_names(included, name_to_module)
    write_output(canon, included, name_to_module)

    print(f'{len(canon)} candidate common functions, {len(excluded)} excluded (globals/closure), {len(included)} generated')
    print(f'{len(set(name_to_module.values()))} modules under {OUTPUT_DIR}')

    return canon


def main():
    parser = argparse.ArgumentParser(description = __doc__)
    parser.add_argument('corpus_root', type = Path, help = 'directory to walk for .dat scripts')
    args = parser.parse_args()

    generate(args.corpus_root)


if __name__ == '__main__':
    main()
