"""Generate the shared common-function library under falcom/ed9/writer/metadata/common/ from a
corpus of decompiled .dat scripts.

Usage:
    python falcom/ed9/writer/scp_writer_gen_common_funcs.py <corpus_root>

Every run is a full rewrite: the whole output directory is cleared and regenerated from scratch, so
hand edits to generated files don't survive - change this script instead.

Algorithm:
    1. Walk the corpus in sorted order, disassembling every is_common_func function
       (round_trip=False, keep_unreachable_code=False) and fingerprinting it (metadata/signature.py).
       The first occurrence of each fingerprint also records the facts steps 3-4 need (global use,
       CALL targets, first syscall) - the fingerprint covers all three, so every copy agrees.
    2. Per name, the majority fingerprint is canonical; ties go to the first occurrence in sorted
       order.
    3. Any canonical function touching LOAD_GLOBAL/SET_GLOBAL is excluded, then the exclusion is
       closed over CALL targets to a fixed point. Every included function's CALL targets must
       themselves be included, or generation fails loudly.
    4. Included functions are grouped by first-syscall subsystem into one module per subsystem
       (no-syscall functions share one module).
    5. Pass 2 re-parses just the files holding an included function's canonical copy and renders
       each from its instruction stream, with the scripts' stack comments - operand-level
       substitution, never text rewriting - while the parse is in hand, then writes the modules.
       A common_all.py module re-exporting every generated module is also written, so a script
       can bring the whole library into scope with one import regardless of which functions its
       own source used.
"""

import argparse
import keyword
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent.parent))

from common.config import default_indent
from falcom.ed9.disasm.ed9_optable import ED9Opcode, ED9OperandType
from falcom.ed9.disasm.formatter import Formatter, FormatterContext
from falcom.ed9.disasm.instruction import Instruction
from falcom.ed9.disasm.instruction_table import OperandType
from falcom.ed9.disasm.llil_dsl_comments import CommentOptions, append_comment, instruction_comments, label_comments
from falcom.ed9.parser.scp import ScpParser
from falcom.ed9.parser.types_parser import Function
from falcom.ed9.writer import scp_writer_helper
from falcom.ed9.writer.metadata import COMMON_LIBRARY_PACKAGE, SCP_WRITER_HELPER_IMPORT
from falcom.ed9.writer.metadata.signature import function_fingerprint, fingerprint_digest

DAT_PATTERN = '*.dat'
OUTPUT_DIR = Path(__file__).resolve().parent / 'metadata' / 'common'
INDEX_PATH = Path(__file__).resolve().parent / 'metadata' / 'common_index.py'
ALL_PATH = Path(__file__).resolve().parent / 'metadata' / 'common_all.py'
MODULE_PREFIX = 'scp_writer_common_'
NO_SYSCALL_MODULE = f'{MODULE_PREFIX}no_syscall'
GENERATED_HEADER_COMMENT = '# Auto-generated by scp_writer_gen_common_funcs.py - do not edit by hand'
LIBRARY_COMMENTS = CommentOptions()     # the stack comments, always; the opt-in kinds are for scripts only

# Every name a generated module's own "from ...scp_writer_helper import *" line brings into scope -
# a canonical function reusing one would silently shadow it for the rest of that module's file.
RESERVED_HELPER_NAMES = {name for name in vars(scp_writer_helper) if not name.startswith('_')}

# Names every generated .py script's own header/footer bind at module scope (scp.py's
# gen_python_header/gen_python_footer) - an imported common function reusing one of these would
# silently rebind it (e.g. a function named 'scena' would replace the writer, breaking the very next
# '@scena.CommonImports()' line the header emits). Unlike RESERVED_HELPER_NAMES this isn't a name
# used inside the library itself, so it can't be discovered by introspecting a library module.
EMITTED_SCRIPT_RESERVED_NAMES = {'scena', 'globalvars', 'commonImports', 'main'}


@dataclass
class FunctionFacts:
    """What decides a function's inclusion and module - the same for every copy with its fingerprint"""
    touches_global: bool        # the exclusion trigger
    call_targets: set[str]      # the closure input
    subsystem: int | None       # the module-grouping key: the first SYSCALL's subsystem


def collect_paths(corpus_root: Path) -> list[Path]:
    return sorted(corpus_root.rglob(DAT_PATTERN))


def function_facts(parser: ScpParser, func: Function) -> FunctionFacts:
    instructions = parser.get_instructions(func)
    return FunctionFacts(
        touches_global  = any(inst.opcode in (ED9Opcode.LOAD_GLOBAL, ED9Opcode.SET_GLOBAL) for inst in instructions),
        call_targets    = {parser.get_func_name_from_func_id(op.value) for inst in instructions for op in inst.operands
                           if op.descriptor.type == ED9OperandType.Func},
        subsystem       = next((inst.operands[0].value for inst in instructions if inst.opcode == ED9Opcode.SYSCALL), None),
    )


def collect_occurrences(paths: list[Path]) -> tuple[dict[str, list[tuple[str, int]]], dict[str, FunctionFacts]]:
    """Pass 1: fingerprint every is_common_func occurrence. name -> [(digest, file_idx), ...], and digest -> facts
    (from its first occurrence)"""
    occurrences: dict[str, list[tuple[str, int]]] = {}
    facts_by_digest: dict[str, FunctionFacts] = {}

    for file_idx, path in enumerate(paths):
        parser, functions = ScpParser.load(path, round_trip = False, keep_unreachable_code = False)

        for func in functions:
            if not func.is_common_func:
                continue

            digest = fingerprint_digest(function_fingerprint(parser, func))
            occurrences.setdefault(func.name, []).append((digest, file_idx))
            if digest not in facts_by_digest:
                facts_by_digest[digest] = function_facts(parser, func)

    return occurrences, facts_by_digest


def select_canonical(occurrences: dict[str, list[tuple[str, int]]]) -> dict[str, tuple[str, int]]:
    """Per name: the majority digest, ties broken by earliest first occurrence. name -> (digest, file_idx)"""
    canonical = {}

    for name, entries in occurrences.items():
        counts = Counter(digest for digest, _file_idx in entries)

        first_seen: dict[str, int] = {}
        for digest, file_idx in entries:  # entries are already in ascending file_idx order
            first_seen.setdefault(digest, file_idx)

        best_digest = max(counts, key = lambda d: (counts[d], -first_seen[d]))
        canonical[name] = (best_digest, first_seen[best_digest])

    return canonical


def verify_canonical_function(parser: ScpParser, func: Function, path: Path, expected_digest: str) -> tuple[list[Instruction], set[int]]:
    """Verify func's fingerprint still matches pass 1's selection, and that every branch target it
    contains lands on a retained instruction - both fail loudly instead of letting a later stage (a
    corrupted digest, or the writer's own label xref patching) produce a confusing error. Returns
    the function's reachable instructions and referenced offsets for render_function to use."""
    digest = fingerprint_digest(function_fingerprint(parser, func))
    if digest != expected_digest:
        raise RuntimeError(f'{func.name}: fingerprint changed between pass 1 and pass 2 ({path})')

    instructions = parser.get_instructions(func)
    referenced_offsets = Formatter.find_referenced_offsets(func.entry_block)

    # Every branch target must land on a real instruction, or render_function would emit a jump to
    # a label that's never placed - the writer would only catch that later, as an undefined-label
    # error naming a UUID label at compile time. Mirrors formatter.py's own invariant
    # (referenced_offsets <= block_start_offsets) instead of relying on that check running elsewhere.
    unresolved = referenced_offsets - {inst.offset for inst in instructions}
    if unresolved:
        targets = ', '.join(f'0x{offset:X}' for offset in sorted(unresolved))
        raise RuntimeError(f'{func.name} ({path}): branch target(s) {targets} do not land on a retained instruction')

    return instructions, referenced_offsets


def compute_excluded(facts: dict[str, FunctionFacts]) -> set[str]:
    """Direct global-var users, then closed over CALL targets to a fixed point"""
    excluded = {name for name, fact in facts.items() if fact.touches_global}

    changed = True
    while changed:
        changed = False
        for name, fact in facts.items():
            if name in excluded:
                continue

            if any(target in excluded for target in fact.call_targets):
                excluded.add(name)
                changed = True

    return excluded


def assign_modules(included: set[str], facts: dict[str, FunctionFacts]) -> dict[str, str]:
    name_to_module = {}
    for name in included:
        subsystem = facts[name].subsystem
        name_to_module[name] = f'{MODULE_PREFIX}{subsystem}' if subsystem is not None else NO_SYSCALL_MODULE

    return name_to_module


def module_suffix(module_key: str) -> str:
    """The subsystem number, or 'no_syscall' - module_key with the common prefix stripped"""
    return module_key[len(MODULE_PREFIX):]


def module_alias(module_key: str) -> str:
    return 'common_' + module_suffix(module_key)


def validate_names(included: set[str], name_to_module: dict[str, str]):
    """Every generated name must be a usable, non-keyword Python identifier, and can't collide with
    a star-imported helper name, any module's cross-module alias, or a name every emitted script's
    own header/footer binds (scena, commonImports, ...) - any of those would silently shadow the
    real one, either inside the library module that defines it or inside the first script that
    imports it. Reserves every module's alias, not just the ones the function's own module currently
    needs, so a name that's safe today can't start colliding after a later regen adds a new
    cross-module call."""
    all_aliases = {module_alias(module_key) for module_key in set(name_to_module.values())}
    reserved = RESERVED_HELPER_NAMES | all_aliases | EMITTED_SCRIPT_RESERVED_NAMES

    for name in included:
        if not name.isidentifier() or keyword.iskeyword(name):
            raise RuntimeError(f'{name!r} is not a usable Python function name')

        if name in reserved:
            raise RuntimeError(f'{name!r} ({name_to_module[name]}) collides with a reserved name (opcode helper, cross-module alias, or emitted-script binding)')


def render_function(parser: ScpParser, func: Function, path: Path, expected_digest: str, name_to_module: dict[str, str]) -> list[str]:
    """The function's final lines: branch targets become genLabel() locals, CALL targets a bare name or common_N.name,
    every other operand its formatted text; the stack comments the scripts get (llil_dsl_comments), always on"""
    instructions, referenced_offsets = verify_canonical_function(parser, func, path, expected_digest)
    formatter_context = FormatterContext(
        get_func_name_from_func_id = parser.get_func_name_from_func_id,
        get_global_name_from_index = parser.get_global_name_from_index,
    )
    own_module = name_to_module[func.name]
    indent = default_indent()
    param_str = ', '.join(Formatter.format_param(i, param) for i, param in enumerate(func.params))

    offset_to_local = {offset: f'L{i}' for i, offset in enumerate(sorted(referenced_offsets))}

    lines = [f'def {func.name}({param_str}):']

    for local in offset_to_local.values():
        lines.append(f'{indent}{local} = genLabel()')

    for inst in instructions:
        if inst.offset in offset_to_local:
            label_line = f'label({offset_to_local[inst.offset]})'
            lines.append(indent + append_comment(label_line, label_comments(func.stack_layout, inst.offset, LIBRARY_COMMENTS)))

        args = []
        for op in inst.operands:
            if op.descriptor.type == OperandType.Offset:
                args.append(offset_to_local[op.value])

            elif op.descriptor.type == ED9OperandType.Func:
                callee = parser.get_func_name_from_func_id(op.value)
                callee_module = name_to_module[callee]
                args.append(callee if callee_module == own_module else f'{module_alias(callee_module)}.{callee}')

            else:
                args.append(op.descriptor.format_operand(op, formatter_context))

        code = f'{inst.descriptor.mnemonic}({", ".join(args)})'
        lines.append(indent + append_comment(code, instruction_comments(func.stack_layout, inst, LIBRARY_COMMENTS)))

    if not instructions:
        lines.append(f'{indent}pass')

    return lines


def render_included_functions(canonical: dict[str, tuple[str, int]], included: set[str], paths: list[Path],
                              name_to_module: dict[str, str]) -> dict[str, list[str]]:
    """Pass 2: re-parse only the files holding an included function's canonical copy (grouped, so a file shared by
    many names is parsed once) and render those functions while the parse is in hand"""
    names_by_file_idx: dict[int, list[str]] = {}
    for name, (_digest, file_idx) in canonical.items():
        if name in included:
            names_by_file_idx.setdefault(file_idx, []).append(name)

    rendered: dict[str, list[str]] = {}

    for file_idx, names in names_by_file_idx.items():
        path = paths[file_idx]
        parser, functions = ScpParser.load(path, round_trip = False, keep_unreachable_code = False)
        functions_by_name = {func.name: func for func in functions}

        for name in names:
            expected_digest, _ = canonical[name]
            rendered[name] = render_function(parser, functions_by_name[name], path, expected_digest, name_to_module)

    return rendered


def render_module(module_key: str, names: list[str], rendered: dict[str, list[str]], facts: dict[str, FunctionFacts], name_to_module: dict[str, str]) -> str:
    imported_modules = sorted({
        name_to_module[callee]
        for name in names
        for callee in facts[name].call_targets
        if name_to_module[callee] != module_key
    })

    lines = [
        f'"""Common-function library, subsystem {module_suffix(module_key)}"""',
        '',
        GENERATED_HEADER_COMMENT,
        '',
        SCP_WRITER_HELPER_IMPORT,
    ]
    # Two generated modules can import each other (a function in A calls one in B and vice versa).
    # Safe: "import x.y as z" only binds the module object here, at import time; every reference to
    # z.callee happens inside a function body, executed later, by which point both modules have
    # finished importing - the same reason a script's own manifest can import from either freely.
    lines.extend(f'import {COMMON_LIBRARY_PACKAGE}.{other} as {module_alias(other)}' for other in imported_modules)
    lines.append('')

    # Only this module's own functions are re-exported, not the helper's star-imported names - a second
    # star import of those (common_all) turns aliases like Value32 into variables for type checkers
    ordered = sorted(names)
    lines.append('__all__ = (')
    lines.extend(f'    {name!r},' for name in ordered)
    lines.append(')')
    lines.append('')

    for name in ordered:
        lines.extend(rendered[name])
        lines.append('')
        lines.append('')

    return '\n'.join(lines).rstrip() + '\n'


def render_index(canonical: dict[str, tuple[str, int]], name_to_module: dict[str, str]) -> str:
    lines = [
        '"""Index of the common-function library: name -> (module, fingerprint digest)"""',
        '',
        GENERATED_HEADER_COMMENT,
        '',
        'COMMON_FUNCTIONS = {',
    ]
    for name in sorted(name_to_module):
        lines.append(f"    {name!r}: ({name_to_module[name]!r}, {canonical[name][0]!r}),")

    lines.append('}')
    return '\n'.join(lines) + '\n'


def render_all(module_keys: list[str]) -> str:
    lines = [
        '"""Every common-function library module, re-exported in one place.',
        '',
        'Every generated script imports this unconditionally (falcom/ed9/parser/scp.py\'s',
        'gen_python_header), so the whole library is always in scope - not just the functions a',
        'script\'s own source happened to use - for adding a common function call by hand.',
        '',
        'COMMON_LIBRARY_GENERATED is False when this package hasn\'t been generated yet (a fresh',
        'checkout before scp_writer_gen_common_funcs.py has been run) - match_library_functions',
        'checks it before matching anything, so an ungenerated library safely falls back to fully',
        'inline output instead of a manifest that would reference an undefined name."""',
        '',
        GENERATED_HEADER_COMMENT,
        '',
        'from common.logging import log as _log',
        '',
        'try:',
    ]
    lines.extend(f'    from {COMMON_LIBRARY_PACKAGE}.{module_key} import *' for module_key in module_keys)
    lines.append('    COMMON_LIBRARY_GENERATED = True')
    lines.append('except ModuleNotFoundError:')
    lines.append("    _log.info('Shared common-function library not generated - run falcom/ed9/writer/scp_writer_gen_common_funcs.py <corpus_root> to build it')")
    lines.append('    COMMON_LIBRARY_GENERATED = False')
    return '\n'.join(lines) + '\n'


def write_output(canonical: dict[str, tuple[str, int]], facts: dict[str, FunctionFacts], rendered: dict[str, list[str]], name_to_module: dict[str, str]):
    for stale in OUTPUT_DIR.glob('*.py'):
        stale.unlink()

    OUTPUT_DIR.mkdir(parents = True, exist_ok = True)
    (OUTPUT_DIR / '__init__.py').write_text('"""Generated common-function library modules, one per syscall subsystem"""\n', encoding = 'utf-8', newline = '\n')

    names_by_module: dict[str, list[str]] = {}
    for name in rendered:
        names_by_module.setdefault(name_to_module[name], []).append(name)

    for module_key, names in names_by_module.items():
        text = render_module(module_key, names, rendered, facts, name_to_module)
        (OUTPUT_DIR / f'{module_key}.py').write_text(text, encoding = 'utf-8', newline = '\n')

    INDEX_PATH.write_text(render_index(canonical, name_to_module), encoding = 'utf-8', newline = '\n')
    ALL_PATH.write_text(render_all(sorted(names_by_module)), encoding = 'utf-8', newline = '\n')


def generate(corpus_root: Path):
    paths = collect_paths(corpus_root)
    occurrences, facts_by_digest = collect_occurrences(paths)
    canonical = select_canonical(occurrences)
    facts = {name: facts_by_digest[digest] for name, (digest, _file_idx) in canonical.items()}

    excluded = compute_excluded(facts)
    included = set(canonical) - excluded

    for name in included:
        for target in facts[name].call_targets:
            if target not in included:
                raise RuntimeError(f'{name}: CALL target {target!r} is excluded or not a common function')

    name_to_module = assign_modules(included, facts)
    validate_names(included, name_to_module)
    rendered = render_included_functions(canonical, included, paths, name_to_module)
    write_output(canonical, facts, rendered, name_to_module)

    print(f'{len(canonical)} candidate common functions, {len(excluded)} excluded (globals/closure), {len(included)} generated')
    print(f'{len(set(name_to_module.values()))} modules under {OUTPUT_DIR}')


def main():
    parser = argparse.ArgumentParser(description = __doc__)
    parser.add_argument('corpus_root', type = Path, help = 'directory to walk for .dat scripts')
    args = parser.parse_args()

    generate(args.corpus_root)


if __name__ == '__main__':
    main()
