"""Every common-function library module, re-exported in one place.

Every generated script imports this unconditionally (falcom/ed9/parser/scp.py's
gen_python_header), so the whole library is always in scope - not just the functions a
script's own source happened to use - for adding a common function call by hand.

COMMON_LIBRARY_GENERATED is False when this package hasn't been generated yet (a fresh
checkout before scp_writer_gen_common_funcs.py has been run) - match_library_functions
checks it before matching anything, so an ungenerated library safely falls back to fully
inline output instead of a manifest that would reference an undefined name."""

# Auto-generated by scp_writer_gen_common_funcs.py - do not edit by hand

from common.logging import log

try:
    from falcom.ed9.writer.metadata.common.scp_writer_common_0 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_1 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_10 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_11 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_12 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_13 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_14 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_15 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_16 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_17 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_18 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_19 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_2 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_20 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_21 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_22 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_23 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_24 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_25 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_26 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_27 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_3 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_4 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_5 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_6 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_7 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_8 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_9 import *
    from falcom.ed9.writer.metadata.common.scp_writer_common_no_syscall import *
    COMMON_LIBRARY_GENERATED = True
except ModuleNotFoundError:
    log.info('Shared common-function library not generated - run falcom/ed9/writer/scp_writer_gen_common_funcs.py <corpus_root> to build it')
    COMMON_LIBRARY_GENERATED = False
